spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shoppingweb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: zgb159632

  mail:
    protocol: smtp
    host: smtp.163.com
    port: 25
    username: 15915912344@163.com
    password: RVNIWWVVGBBFIWEB
    default-encoding: utf-8
    properties:
      mail:
        debug: false

  mvc:
    static-path-pattern: /img/**
  web:
    resources:
      static-locations: file:/home/imgUpload/

mybatis:
  configuration:
    map-underscore-to-camel-case: true

